### ISSUE TITLE
做了一个像素渲染的UI

### ISSUE THREAD

**Issue by 958877748** [fairygui/fairygui.io#10]
PIXI.ApplicationOptions.resolution>1的时候 文本有问题,看不到,
PIXI.ApplicationOptions.resolution = 1 时  文本就正常了

**Comment by 958877748** [comment]
文本的可见区域没有放大

**Comment by xiaoguzhu** [comment]
pixi问题到fairygui-pixi sdk的github下提issue。

**Comment by 958877748** [comment]
好的
