### ISSUE TITLE
关于中制作共享Blank丢失

### ISSUE THREAD

**Issue by gjmvvv** [fairygui/fairygui.io#12]
https://github.com/fairygui/fairygui.io/blob/master/src/about/index.md

**Comment by xiaoguzhu** [comment]
没看懂什么意思？

**Comment by gjmvvv** [comment]
主界面  关于下面4个共享人员 Blank 点击下是个空界面


发件人： guzhu
发送时间： 2019-04-04 14:43
收件人： fairygui/fairygui.io
抄送： Mr.Kevin(郭进明); Author
主题： Re: [fairygui/fairygui.io] 关于中制作共享Blank丢失 (#12)
没看懂什么意思？

**Comment by gjmvvv** [comment]
发件人： guzhu
发送时间： 2019-04-04 14:43
收件人： fairygui/fairygui.io
抄送： Mr.Kevin(郭进明); Author
主题： Re: [fairygui/fairygui.io] 关于中制作共享Blank丢失 (#12)
没看懂什么意思？
―
